### ISSUE TITLE
No coverage of System.exit with Jacoco

### ISSUE THREAD

**Issue by AlexLefranc** [stefanbirkner/system-rules#79] opened 2020-02-11 12:07 UTC
Hi,

I try your rules (really useful for env variables), but when I use jacoco, the report don't see coverage of System.exit with ExpectedSystemExit. Do you know this problem ?

Thanks for your help, and your work.

**Comment by stefanbirkner** [comment] 2020-04-11 13:29
Sorry for the late answer. This is a duplicate of #4 and therefore a problem of JaCoCo: jacoco/jacoco#117

**Closed by stefanbirkner** 2020-04-11 13:29 UTC
Labels: JaCoCo problem
